import { defineManifest } from '@crxjs/vite-plugin';

export default defineManifest({
  manifest_version: 3,
  name: 'TubeBox',
  description:
    'TubeBox detects MP4 / M3U8 on web pages and downloads locally. YouTube is not supported.',
  version: '0.1.0',
  action: {
    default_popup: 'src/popup/index.html',
    default_title: 'TubeBox',
    default_icon: {
      '16': 'icons/icon16.png',
      '48': 'icons/icon48.png',
      '128': 'icons/icon128.png',
    },
  },
  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },
  permissions: ['storage', 'tabs', 'webRequest'],
  host_permissions: ['http://*/*', 'https://*/*'],
  content_scripts: [
    {
      matches: ['*://*.instagram.com/*', '*://instagram.com/*'],
      js: ['src/content/instagram-main.ts'],
      run_at: 'document_start',
      world: 'MAIN',
    },
    {
      matches: ['*://*.instagram.com/*', '*://instagram.com/*'],
      js: ['src/content/instagram.ts'],
      run_at: 'document_idle',
    },
    {
      matches: ['*://*.tiktok.com/*', '*://tiktok.com/*'],
      js: ['src/content/tiktok.ts'],
      run_at: 'document_idle',
    },
    {
      matches: [
        '*://*.facebook.com/*',
        '*://facebook.com/*',
        '*://*.fb.com/*',
        '*://fb.com/*',
      ],
      js: ['src/content/facebook.ts'],
      run_at: 'document_idle',
    },
    {
      matches: [
        '*://*.twitter.com/*',
        '*://twitter.com/*',
        '*://*.x.com/*',
        '*://x.com/*',
      ],
      js: ['src/content/twitter.ts'],
      run_at: 'document_idle',
    },
    {
      matches: ['*://*.bilibili.com/*', '*://bilibili.com/*'],
      js: ['src/content/bilibili.ts'],
      run_at: 'document_idle',
    },
    {
      matches: ['*://*.dailymotion.com/*', '*://dailymotion.com/*'],
      js: ['src/content/dailymotion.ts'],
      run_at: 'document_idle',
    },
    {
      matches: [
        '*://*.vk.com/*',
        '*://vk.com/*',
        '*://*.vkvideo.ru/*',
        '*://vkvideo.ru/*',
      ],
      js: ['src/content/vk.ts'],
      run_at: 'document_idle',
    },
    {
      matches: ['*://*.ixigua.com/*', '*://ixigua.com/*'],
      js: ['src/content/ixigua-main.ts'],
      run_at: 'document_idle',
      world: 'MAIN',
    },
    {
      matches: ['*://*.ixigua.com/*', '*://ixigua.com/*'],
      js: ['src/content/ixigua.ts'],
      run_at: 'document_idle',
    },
    {
      matches: [
        '*://*.928hd.tv/*',
        '*://928hd.tv/*',
        '*://*.showhd9.com/*',
        '*://showhd9.com/*',
      ],
      js: ['src/content/niche-hls.ts'],
      run_at: 'document_idle',
    },
    {
      matches: ['http://*/*', 'https://*/*'],
      exclude_matches: [
        '*://*.instagram.com/*',
        '*://instagram.com/*',
        '*://*.tiktok.com/*',
        '*://tiktok.com/*',
        '*://*.facebook.com/*',
        '*://facebook.com/*',
        '*://*.fb.com/*',
        '*://fb.com/*',
        '*://*.twitter.com/*',
        '*://twitter.com/*',
        '*://*.x.com/*',
        '*://x.com/*',
        '*://*.bilibili.com/*',
        '*://bilibili.com/*',
        '*://*.dailymotion.com/*',
        '*://dailymotion.com/*',
        '*://*.vk.com/*',
        '*://vk.com/*',
        '*://*.vkvideo.ru/*',
        '*://vkvideo.ru/*',
        '*://*.ixigua.com/*',
        '*://ixigua.com/*',
        '*://*.928hd.tv/*',
        '*://928hd.tv/*',
        '*://*.showhd9.com/*',
        '*://showhd9.com/*',
        '*://*.youtube.com/*',
        '*://youtube.com/*',
        '*://youtu.be/*',
      ],
      js: ['src/content/generic.ts'],
      run_at: 'document_idle',
    },
  ],
  icons: {
    '16': 'icons/icon16.png',
    '48': 'icons/icon48.png',
    '128': 'icons/icon128.png',
  },
  web_accessible_resources: [
    {
      resources: ['src/dl/index.html', 'assets/*'],
      matches: ['http://*/*', 'https://*/*'],
    },
  ],
});
